[[navbar]]
  identifier = "about"
  name = "Home"
  url = "/"
  parent = ""
  weight = 1
[[navbar]]
  identifier = "research"
  name = "Research"
  url = "/Research/"
  parent = ""
  weight = 2
[[navbar]]
  identifier = "CV"
  name = "CV"
  url = "../CV_Shervin_Sahba.pdf"
  parent = ""
  weight = 4
[[navbar]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  parent = ""
  weight = 5